### ISSUE TITLE
The 'fit' extras has to be installed

### ISSUE THREAD

**Issue by MarcusKreol** [metaDMG-dev/metaDMG-core#17]
Hi,
I recently installed metaDMG using Conda, and this error continues to pop up whenever I run metaDMG compute:
> The 'fit' extras has to be installed: pip install "metaDMG[fit]"
> Aborted.
 Since I used the option "metaDMG[all]" during installation, this is definitely not literally the real error. As is expected, when running `pip install "metaDMG[fit]"`, I'm noticed that all requirements were already satisfied.
Has anyone else encountered the same issue? Thanks a lot if there's any solutions.

**Comment by Louis-MG** [comment]
I think I solved it.

Changing the code in `utils.py` from:
```python
def check_metaDMG_fit():
    try:
        import metaDMG.fit

    except ModuleNotFoundError:
        print("""The 'fit' extras has to be installed: pip install "metaDMG[fit]" """)
        raise typer.Abort()
```
to 
```python3
def check_metaDMG_fit():
    import metaDMG.fit
```
yields the error:
```
ModuleNotFoundError: No module named 'jax.linear_util'
```
Which is explained by https://stackoverflow.com/questions/78210393/cannot-import-name-linear-util-from-jax, so changing the version using:
```
pip install jax==0.4.16
pip install jaxlib==0.4.16
```
Then I obtained the new error:
```python
AttributeError: module 'scipy.linalg' has no attribute 'tril'
```
Which is explained by https://github.com/octo-models/octo/issues/71 and solved by:
```
pip install scipy==1.12.0
```
It seems to solve the module errors, but then I get `KeyError: 'loggers'` when metaDMG tries to create the log file. Trying to solve this now.

**Comment by MarcusKreol** [comment]
Solved. Thanks very much @Louis-MG

**Comment by fistorres** [comment]
I still get the error 'AttributeError: module 'scipy.linalg' has no attribute 'tril'' with scipy==1.12

This is my conda env:
name: scCoda
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_1
  - blas=1.0=openblas
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - curl=8.9.1=hdbd6064_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_1
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_1
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.29.5=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - ml_dtypes=0.4.0=py39h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - openssl=3.0.15=h5eee18b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pango=1.50.7=h05da053_0
  - parso=0.8.4=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=3.10.0=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd3eb1b0_1
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - pyzmq=25.1.2=py39h6a678d5_0
  - r-base=4.3.1=h1ae530e_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - tktable=2.10=h3d55465_1
  - tornado=6.4.2=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.1
      - anndata==0.10.8
      - array-api-compat==1.9.1
      - arrow==1.3.0
      - arviz==0.17.1
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - chex==0.1.88
      - cloudpickle==3.1.0
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - custom-inherit==2.4.1
      - cycler==0.12.1
      - decoupler==1.8.0
      - dm-tree==0.1.8
      - docrep==0.3.2
      - equinox==0.11.10
      - et-xmlfile==2.0.0
      - ete3==3.1.3
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - flax==0.8.5
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - get-annotations==0.1.2
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5netcdf==1.4.1
      - h5py==3.12.1
      - humanize==4.11.0
      - idna==3.10
      - igraph==0.11.8
      - importlib-resources==6.4.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jax==0.4.30
      - jaxlib==0.4.30
      - jaxopt==0.8.3
      - jaxtyping==0.2.36
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - keras==3.7.0
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - libclang==18.1.1
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - lineax==0.0.7
      - llvmlite==0.43.0
      - loguru==0.7.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mizani==0.11.4
      - ml-collections==0.1.1
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.2.4
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - muon==0.1.6
      - namex==0.0.8
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpyro==0.16.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.13.1
      - orbax-checkpoint==0.6.4
      - ott-jax==0.5.0
      - packaging==24.2
      - pandas==2.2.3
      - patsy==1.0.1
      - pertpy==0.6.0
      - pexpect==4.9.0
      - pillow==11.0.0
      - plotnine==0.13.6
      - ply==3.11
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.1
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyomo==6.8.2
      - pyparsing==3.2.0
      - pypng==0.20220715.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.15
      - pyqt5-sip==12.16.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - reportlab==4.2.5
      - requests==2.32.3
      - rich==13.9.4
      - rpy2==3.5.17
      - scanpy==1.10.3
      - sccoda==0.1.9
      - scikit-learn==1.6.0
      - scikit-misc==0.3.1
      - scipy==1.12.0
      - scvi-tools==1.1.6.post2
      - seaborn==0.13.2
      - session-info==1.0.0
      - six==1.17.0
      - sparsecca==0.3.1
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.69
      - termcolor==2.5.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - torch==2.5.1
      - torchmetrics==1.6.0
      - toyplot==2.0.0
      - toytree==3.0.6
      - tqdm==4.67.1
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - tzlocal==5.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - xarray==2024.7.0
      - xarray-einstats==0.7.0
      - yarl==1.18.3
prefix: /home/ubuntu/miniconda3/envs/scCoda

**Comment by charliep** [comment]
Is there any reason not to put this fix into the main branch? We just installed metaDMG and the current release fails the same way. 

thanks,
charlie
